### ISSUE TITLE
Agent failed with sigsegv

### ISSUE THREAD

**Issue by Vanuan** [nohaapav/swarmpit#262]
**Description**

**Steps to reproduce the issue:**
Don't know how to reproduce, it just happens on some machines

```
2018/07/05 08:35:56 INFO: Waiting for Swarmpit...
2018/07/05 08:36:01 INFO: Swarmpit OK
2018/07/05 08:36:01 INFO: Event collector started.
2018/07/05 08:36:01 INFO: Stats collector started.
2018/07/05 08:36:01 INFO: Swarmpit agent listening on port 8080
panic: runtime error: invalid memory address or nil pointer dereference
[signal SIGSEGV: segmentation violation code=0x1 addr=0x180 pc=0x6b5767]

goroutine 9643 [running]:
github.com/swarmpit/agent/swarmpit/task.ContainerUsage(0xc4200f9e00, 0xc4207da140, 0x40, 0x0, 0x0, 0x0, 0x0, 0x0, 0x0, 0x0, ...)
	/home/travis/gopath/src/github.com/swarmpit/agent/swarmpit/task/stats.go:159 +0x437
github.com/swarmpit/agent/swarmpit/task.ContainersUsage.func1(0xc4202d8310, 0xc4200f9e00, 0xc4202d8360, 0xc4204b6540, 0xc4207da140, 0x40, 0xc4206b83c0, 0x1, 0x4, 0xc420015600, ...)
	/home/travis/gopath/src/github.com/swarmpit/agent/swarmpit/task/stats.go:126 +0x87
created by github.com/swarmpit/agent/swarmpit/task.ContainersUsage
	/home/travis/gopath/src/github.com/swarmpit/agent/swarmpit/task/stats.go:124 +0x1ef

```

**What happens:**

Container dies

**What should happen:**

**Additional information (e.g. docker version, cluster setup,...):**

**Comment by Vanuan** [comment]
The issue appears to be in here:
task.ContainerUsage(0xc4200f9e00, 0xc4207da140, 0x40, 0x0, 0x0, 0x0, 0x0, 0x0, 0x0, 0x0, ...)

https://github.com/swarmpit/agent/blob/adff5c79871ee8f7edac3b61febb4b903aaba0e8/swarmpit/task/stats.go#L159
https://github.com/swarmpit/agent/blob/adff5c79871ee8f7edac3b61febb4b903aaba0e8/swarmpit/task/stats.go#L126
https://github.com/swarmpit/agent/blob/adff5c79871ee8f7edac3b61febb4b903aaba0e8/swarmpit/task/stats.go#L124


```
	v *types.StatsJSON
	dec.Decode(&v);
	previousCPU = v.PreCPUStats.CPUUsage.TotalUsage
```

**Comment by Vanuan** [comment]
So it looks like docker daemon returned missing precpu_stats.

According to documentation it can be empty:

https://github.com/docker/engine-api/blob/4290f40c056686fcaa5c9caf02eac1dde9315adf/types/stats.go#L100-L107

> The "omitempty" option specifies that the field should be omitted from the encoding if the field has an empty value, defined as false, 0, a nil pointer, a nil interface value, and any empty array, slice, map, or string.

**Comment by Aneadiel** [comment]
Still present in agent version 2.2, swarmpit version 1.9 and db couchdb 2.3.0

**Comment by michalblaha** [comment]
Still present,  all agents (agent:latest, Docker 20.10.11 && 20.10.12) , @lumir-mrkva & @nohaapav 

Log:
```
2022/02/04 04:15:41 INFO: Waiting for Swarmpit...
 2022/02/04 04:15:46 INFO: Swarmpit OK
 2022/02/04 04:15:46 INFO: Event collector started.
 2022/02/04 04:15:46 INFO: Stats collector started.
 panic: runtime error: invalid memory address or nil pointer dereference
 [signal SIGSEGV: segmentation violation code=0x1 addr=0x180 pc=0x845a6c]
 
 goroutine 1576 [running]:
 github.com/swarmpit/agent/swarmpit/task.ContainerUsage(0xc00011de80, 0xc0001aed80, 0x40, 0x0, 0x0, 0x0, 0x0, 0x0, 0x0, 0x0, ...)
 	/build/swarmpit/task/stats.go:157 +0x48c
 github.com/swarmpit/agent/swarmpit/task.ContainersUsage.func1(0xc000027cc0, 0xc00011de80, 0xc000027cb8, 0xc000220c20, 0xc0001aed80, 0x40, 0xc0003c0700, 0x1, 0x4, 0xc000119a70, ...)
 	/build/swarmpit/task/stats.go:124 +0x87
 created by github.com/swarmpit/agent/swarmpit/task.ContainersUsage
 	/build/swarmpit/task/stats.go:122 +0x212
 ```

**Comment by frapell** [comment]
This is happening for us in 1 node, any advice?

using swarmpit/agent:latest
and
```
Client: Docker Engine - Community
 Version:           23.0.1
 API version:       1.42
 Go version:        go1.19.5
 Git commit:        a5ee5b1
 Built:             Thu Feb  9 19:47:01 2023
 OS/Arch:           linux/amd64
 Context:           default

Server: Docker Engine - Community
 Engine:
  Version:          23.0.1
  API version:      1.42 (minimum version 1.12)
  Go version:       go1.19.5
  Git commit:       bc3805a
  Built:            Thu Feb  9 19:47:01 2023
  OS/Arch:          linux/amd64
  Experimental:     false
 containerd:
  Version:          1.6.16
  GitCommit:        31aa4358a36870b21a992d3ad2bef29e1d693bec
 runc:
  Version:          1.1.4
  GitCommit:        v1.1.4-0-g5fd4c4d
 docker-init:
  Version:          0.19.0
  GitCommit:        de40ad0
```

**Comment by mrq1911** [comment]
fixed in swarmpit/agent#17 and swarmpit/agent#18 — the stats decoder left a nil pointer that was dereferenced on the next line. duplicate of the more recent #736.
